<section class="hero">
        <div class="contain mb-5">
			<div class="dot dot-two"></div>
			<div class="row">
				<div class="dot dot-one"></div>
                <div class="col-md-12 text-center">
                   <h1 class="text-light">Site Terms</h1>
                </div>
				<div class="dot dot-three"></div>
				<div class="dot dot-four"></div>
            </div>
        </div>
		<section class="waves">
            <svg viewBox="0 0 100 25">
				<path fill="#736DEA" opacity="0.5" d="M0 30 V15 Q30 3 60 15 V30z"></path>
                <path fill="#ffffff" d="M0 30 V12 Q30 17 55 12 T100 11 V30z"></path>
            </svg>
        </section>
</section>

<div class="container">
    <div class="row">
       <div class="col-md-12 pg">
       <p>Last Updated:&nbsp;<strong>June 27th, 2019</strong></p>
       <p>These Terms do not alter in any way the terms or conditions of any other agreement you may have with Mysite, or its subsidiaries or affiliates, for products, services or otherwise.</p>
       <p>Any changes or modification will be effective immediately upon posting of the revisions on the Site, and you waive any right you may have to receive specific notice of such changes or modifications.&nbsp; Your continued use of this Site following the posting of changes or modifications will confirm your acceptance of such changes or modifications.&nbsp; Therefore, you should frequently review the Terms and applicable policies from time-to-time to understand the terms and conditions that apply to your use of the Site.&nbsp; If you do not agree to the amended terms, you must stop using the Site.</p>
       <p><strong>1. Privacy Policy</strong></p>
       <p>Please refer to our&nbsp;<a href="<?php echo base_url();?>privacy-policy">Privacy Policy</a>&nbsp;for information about how Mysite collects, uses and discloses personal information from its users of the Site.</p>
       <p><strong>2. Eligibility, Registration and Account</strong></p>
       <p>By accessing or using the Site, you represent and warrant that you are a resident of the Sri Lanka and at least 18 years old.&nbsp; If you are not 18 or older, you may only use the Site under the supervision of a parent or legal guardian who agrees to be bound by these Terms.&nbsp; If you are using the Site on behalf of any entity, you represent and warrant that you are authorized to accept these Terms on such entity’s behalf, and that such entity agrees to indemnify you and Mysite for violations of these Terms.</p>       
       <p>In order to access certain areas and features of our Site, you will need to register for an account.&nbsp; You agree to (a)&nbsp;provide accurate, truthful, current and complete information when creating an account; (b)&nbsp;maintain and promptly update your account information; (c)&nbsp;maintain the security of your account by not sharing your password with others and restricting access to your account and your computer; (d)&nbsp;promptly notify Mysite if you discover or otherwise suspect any security breaches related to the Site; and (e)&nbsp;take responsibility for all activities that occur under your account and accept all risks of unauthorized access.</p>
       <p><strong>3. Copyright and Limited License</strong></p>
       <p>Unless otherwise indicated, the Site and all content and other materials on the Site, including, without limitation, the Mysite logo, and all designs, text, graphics, pictures, information, data, software, sound files, other files and the selection and arrangement thereof (collectively, the “Site Materials”) are the proprietary property of Mysite or its licensors or users and are protected by Sri Lanka and international copyright laws.</p>
       <p>You are granted a limited, non-transferable, non-exclusive license to access and use the Site and Site Materials; provided, however, that such license is subject to these Terms and does not include: (a) any resale or commercial use of the Site or the Site Materials therein; (b) the distribution, public performance or public display of any Site Materials; (c) modifying or otherwise making any derivative uses of the Site and the Site Materials, or any portion thereof, unless modification or derivative use is specifically provided for under separate terms; (d) use of any data mining, robots or similar data gathering or extraction methods; (e) downloading (other than page caching) of any portion of the Site, the Site Materials or any information contained therein, except as expressly permitted on the Site; or (f) any use of the Site or the Site Materials other than for its intended purpose.&nbsp; Any use of the Site or the Site Materials other than as specifically authorized herein, without the prior written permission of Mysite, is strictly prohibited and will terminate the license granted herein.&nbsp; Such unauthorized use may also violate applicable laws including without limitation copyright and trademark laws and applicable communications regulations and statutes. &nbsp;Unless explicitly stated herein, nothing in these Terms shall be construed as conferring any license to intellectual property rights, whether by estoppel, implication or otherwise.&nbsp; This license is revocable at any time.</p>
       <p><strong>4. Repeat Infringer Policy</strong></p>
       <p>In accordance with the Digital Millennium Copyright Act (“DMCA”) and other applicable law, Mysite has adopted a policy of terminating, in appropriate circumstances and at Mysite’s sole discretion, users or account holders who are deemed to be repeat infringers.&nbsp; Mysite may also at its sole discretion limit access to the Site and/or terminate the accounts of any users who infringe any intellectual property rights of others, whether or not there is any repeat infringement.</p>
       <p><strong>5. Copyright Complaints</strong></p>
       <p>If you believe that anything on the Site infringes upon any copyright which you own or control, you may file a notification of such infringement with our Designated Agent as set forth below.</p>
       <p>Designated Agent to Which Notification Should be Sent:</p>       
       <p>Mysite, Inc.<br>
        ATTN: COPYRIGHT AGENT, LEGAL<br>
        7900 E. Union Ave.,<br>
        Suite 1100<br>
        Denver, CO 80237<br>
        Telephone Number of Designated Agent:&nbsp; 877-944-2490<br>
        E-Mail Address of Designated Agent: &nbsp;legal@Mysite.com</p>
       <p>You should note that if you knowingly misrepresent in your notification that the material or activity is infringing, you will be liable for any damages, including costs and attorneys’ fees, incurred by us or the alleged infringer as the result of our relying upon such misrepresentation in removing or disabling access to the material or activity claimed to be infringing.</p>
       <p><strong>6. Trademarks&nbsp;</strong></p>
       <p>“Mysite,” the Mysite logo and any other Mysite product or service name or slogan contained on the Site are trademarks of Mysite, and may not be copied, imitated or used, in whole or in part, without the prior written permission of Mysite or the applicable trademark holder.&nbsp; You may not use any metatags or any other “hidden text” utilizing “Mysite” or any other name, trademark or product or service name of Mysite without our prior written permission.&nbsp; In addition, the look and feel of the Site, including all page headers, custom graphics, button icons and scripts, is the service mark, trademark and/or trade dress of Mysite and may not be copied, imitated or used, in whole or in part, without our prior written permission.&nbsp; All other trademarks, registered trademarks, product names and Mysite names or logos mentioned in the Site are the property of their respective owners.&nbsp; Reference to any products, services, processes or other information, by trade name, trademark, manufacturer, supplier or otherwise does not constitute or imply endorsement, sponsorship or recommendation thereof by us.</p>
       <p><strong>7. Logos</strong></p>
       <p>You may not use an Mysite logo or other proprietary graphic of Mysite to link to this Site without the express written permission of Mysite.&nbsp; Further, you may not use, frame or utilize framing techniques to enclose any Mysite trademark, logo or other proprietary information, including the images found at the Site, the content of any text or the layout/design of any page or form contained on a page on the Site without Mysite’s express written consent.&nbsp; Except as noted above, you are not conveyed any right or license by implication, estoppel or otherwise in or under any patent, trademark, copyright or proprietary right of Mysite or any third party.</p>
       <p>Mysite makes no claim or representation regarding, and accepts no responsibility for, the quality, content, nature or reliability of third-party websites accessible via hyperlink or websites linking to the Site.&nbsp; Such sites are not under the control of Mysite and Mysite is not responsible for any embedded content or the content of any linked site or any link contained in a linked site, or any review, changes or updates to such sites.&nbsp; Mysite may provide these links as a convenience to you, but the inclusion of any link does not imply affiliation, endorsement or adoption by Mysite of any site or any information contained therein.&nbsp; When you leave the Site, you should be aware that our terms and policies no longer govern, and the policies of those third party sites will apply.&nbsp; You should review the applicable terms and policies, including privacy and data gathering practices, of any site to which you navigate from the Site.</p>
       <p><strong>8. Third Party Content</strong></p>
       <p>Mysite may provide third party content on the Site and may provide links to web pages and content of third parties (collectively, the “Third Party Content”) as a service to those interested in this information.&nbsp; Mysite does not control, endorse or adopt any Third Party Content and makes no representation or warranties of any kind regarding the Third Party Content, including without limitation regarding its accuracy or completeness.&nbsp; You acknowledge and agree that Mysite is not responsible or liable in any manner for any Third Party Content and undertakes no responsibility to update or review any Third Party Content.&nbsp; Users use such Third Party Content contained therein at their own risk.</p>
       <p><strong>9. Submissions&nbsp;</strong></p>
       <p>You may submit questions, comments, suggestions, ideas, plans, notes, drawings, original or creative materials or other information about Mysite, the Site or our products and services (collectively, “Submissions”).&nbsp; &nbsp;Submissions, whether posted to the Site or provided to Mysite by email or otherwise, are non-confidential and shall become the sole property of Mysite.&nbsp; Mysite shall own exclusive rights, including all intellectual property rights, and shall be entitled to the unrestricted use and dissemination of Submissions for any purpose, commercial or otherwise, without acknowledgment or compensation to you.</p>
       <p><strong>10. Indemnification</strong></p>
       <p>You agree to defend, indemnify and hold harmless Mysite, its independent contractors, service providers and consultants, and their respective directors, employees and agents, from and against any claims, damages, costs, liabilities and expenses (including, but not limited to, reasonable attorneys’ fees) arising out of or related to (a) your use of the Site; (b)&nbsp;any Submission you provide; (c) your violation of these Terms; (d) your violation of any rights of another; or (e)&nbsp;your conduct in connection with the Site.&nbsp;</p>
       <p><strong>11. Disclaimer&nbsp;</strong></p>
       <p>EXCEPT AS EXPRESSLY PROVIDED TO THE CONTRARY IN A WRITING BY Mysite, THE SITE AND THE SITE MATERIALS CONTAINED THEREIN ARE PROVIDED ON AN “AS IS” BASIS WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED.&nbsp; Mysite DISCLAIMS ALL OTHER WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT AS TO THE SITE AND THE SERVICES, INCLUDING THE INFORMATION, CONTENT AND MATERIALS CONTAINED THEREIN.&nbsp; Mysite DOES NOT REPRESENT OR WARRANT THAT THE SITE OR SITE MATERIALS ARE ACCURATE, COMPLETE, RELIABLE, CURRENT OR ERROR-FREE.&nbsp; WHILE Mysite ATTEMPTS TO MAKE YOUR ACCESS AND USE OF THE SITE SAFE, Mysite CANNOT AND DOES NOT REPRESENT OR WARRANT THAT THE SITE OR ITS SERVER(S) ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS; THEREFORE, YOU SHOULD USE INDUSTRY-RECOGNIZED SOFTWARE TO DETECT AND DISINFECT VIRUSES FROM ANY DOWNLOAD.</p>
       <p><strong>12. Limitation of Liability</strong></p>
       <p>IN NO EVENT SHALL Mysite, ITS DIRECTORS, MEMBERS, EMPLOYEES OR AGENTS BE LIABLE FOR ANY DIRECT, SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES, OR ANY OTHER DAMAGES OF ANY KIND, INCLUDING BUT NOT LIMITED TO LOSS OF USE, LOSS OF PROFITS OR LOSS OF DATA, WHETHER IN AN ACTION IN CONTRACT, TORT (INCLUDING BUT NOT LIMITED TO NEGLIGENCE) OR OTHERWISE, ARISING OUT OF OR IN ANY WAY CONNECTED WITH THE USE OF OR INABILITY TO USE THE SITE, THE CONTENT OR THE MATERIALS CONTAINED IN OR ACCESSED THROUGH THE SITE, INCLUDING WITHOUT LIMITATION ANY DAMAGES CAUSED BY OR RESULTING FROM RELIANCE BY YOU ON ANY INFORMATION OBTAINED FROM Mysite, OR THAT RESULT FROM MISTAKES, OMISSIONS, INTERRUPTIONS, DELETION OF FILES OR EMAIL, ERRORS, DEFECTS, VIRUSES, DELAYS IN OPERATION OR TRANSMISSION OR ANY FAILURE OF PERFORMANCE, WHETHER OR NOT RESULTING FROM ACTS OF GOD, COMMUNICATIONS FAILURE, THEFT, DESTRUCTION OR UNAUTHORIZED ACCESS TO Mysite’S RECORDS, PROGRAMS OR SERVICES.&nbsp; IN NO EVENT SHALL THE AGGREGATE LIABILITY OF Mysite, WHETHER IN CONTRACT, WARRANTY, TORT (INCLUDING NEGLIGENCE, WHETHER ACTIVE, PASSIVE OR IMPUTED), PRODUCT LIABILITY, STRICT LIABILITY OR OTHER THEORY, ARISING OUT OF OR RELATING TO THE USE OF OR INABILITY TO USE THE SITE OR TO THESE TERMS EXCEED ANY COMPENSATION YOU PAY, IF ANY, TO Mysite FOR ACCESS TO OR USE OF THE SITE. SOME JURISDICTIONS DO NOT ALLOW THE LIMITATION OF LIABILITY IN CONTRACTS WITH CONSUMERS, SO SOME OR ALL OF THESE LIMITATIONS OF LIABILITY MAY NOT APPLY TO YOU.</p>
       <p><strong>13. Modifications to the Site</strong></p>
       <p>Mysite reserves the right to modify or discontinue, temporarily or permanently, the Site, or any features or portions thereof, without prior notice.&nbsp; You agree that Mysite will not be liable for any modification, suspension or discontinuance of the Site, or any part thereof.</p>
       <p><strong>14. Termination&nbsp;</strong></p>
       <p>Mysite reserves the right, without notice and in its sole discretion, to terminate your license to use the Site, and to block or prevent your future access to, and use of, the Site.</p>
       <p><strong>15. Severability&nbsp;</strong></p>
       <p>If any provision of these Terms shall be deemed unlawful, void or for any reason unenforceable, then that provision shall be deemed severable from these Terms and shall not affect the validity and enforceability of any remaining provisions.<strong>&nbsp;</strong></p>
       <p><strong>16. Questions &amp; Contact Information</strong></p>
       <p>Questions or comments about the Site or these Terms may be directed to Mysite by emailing&nbsp;<a href="mailto:support@Mysite.com">support@Mysite.com</a>&nbsp;or calling us at 0718348394.</p>
       </div>
    </div>
</div>